name: CI for Node.js Express

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Use specified Node.js version
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint your code (if you have ESLint configured)
      - name: Run ESLint
        run: npm run lint

      # 5. Run tests
      - name: Run tests
        run: npm test

      # # 6. (Optional) Build step for production artifacts
      # - name: Build
      #   if: exists('package.json') && contains(fromJson('["build"]'), github.event_name)
      #   run: npm run build

  # Optional: Deploy job can go here, e.g. to Heroku/Vercel/AWS,
  # triggered only on pushes to main.
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Deploy to Heroku
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: your-heroku-app-name
  #         heroku_email: your-email@example.com
